/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'ro' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact' | 'modular';
    layout?: ('centered' | 'textLeft' | 'textRight' | 'textOnly' | 'splitScreen') | null;
    splitScreenRightContent?: ('image' | 'blogPosts') | null;
    blogPostsMode?: ('newest' | 'selected') | null;
    selectedBlogPosts?: (string | Post)[] | null;
    contentAlignment?: ('left' | 'center' | 'right') | null;
    backgroundStyle?: ('image' | 'gradient' | 'solid' | 'none') | null;
    backgroundColor?: string | null;
    backgroundImage?: (string | null) | Media;
    gradientColors?: {
      from?: string | null;
      to?: string | null;
      direction?: ('to-b' | 'to-br' | 'to-r' | 'to-tr') | null;
    };
    overlay?: {
      enabled?: boolean | null;
      color?: string | null;
    };
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Alege cum ar trebui afișat link-ul.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
    secondaryImage?: (string | null) | Media;
    bottomText?: string | null;
    showDownArrow?: boolean | null;
  };
  layout: (
    | CallToActionBlock
    | ContactBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | FileListBlock
    | GalleryBlock
    | ListBlock
    | {
        /**
         * Alege stilul de layout - traditional, overlay modern, sau focus pe conținut/imagine
         */
        layout?: ('textLeft' | 'imageLeft' | 'overlay' | 'splitScreen' | 'contentFocus' | 'imageFocus') | null;
        /**
         * Stilul vizual general al secțiunii
         */
        designStyle?: ('standard' | 'premium' | 'tech' | 'minimal' | 'bold') | null;
        content: {
          /**
           * Titlul principal pentru această secțiune
           */
          heading?: string | null;
          headingSize?: ('normal' | 'large' | 'xl' | '2xl') | null;
          /**
           * Subtitlu opțional
           */
          subheading?: string | null;
          /**
           * Text mic deasupra titlului (stilul premium)
           */
          eyebrow?: string | null;
          /**
           * Conținutul principal de text
           */
          text: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          /**
           * Butoane opționale pentru acțiuni
           */
          buttons?:
            | {
                link?: {
                  type?: ('internal' | 'external') | null;
                  reference?: (string | null) | Page;
                  url?: string | null;
                };
                label: string;
                style?: ('primary' | 'secondary' | 'outline') | null;
                id?: string | null;
              }[]
            | null;
        };
        /**
         * Imaginea care se va afișa alături de text
         */
        image: string | Media;
        /**
         * Controlează proporțiile imaginii
         */
        imageAspect?: ('auto' | 'square' | 'landscape' | 'wide' | 'portrait') | null;
        /**
         * Cum să fie aliniat conținutul pe verticală
         */
        verticalAlignment?: ('start' | 'center' | 'end') | null;
        /**
         * Stilul de fundal al secțiunii
         */
        backgroundColor?: ('none' | 'subtle' | 'premium' | 'dark' | 'gradient') | null;
        /**
         * Spațierea verticală a secțiunii
         */
        spacing?: ('compact' | 'standard' | 'large' | 'xl') | null;
        imageStyle?: {
          borderRadius?: ('none' | 'small' | 'medium' | 'large' | 'xl') | null;
          shadow?: ('none' | 'small' | 'medium' | 'large') | null;
          /**
           * Adaugă un overlay pentru textul pe imagine (pentru layout overlay)
           */
          overlay?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'textImage';
      }
    | TimelineBlock
    | FAQBlock
    | HeroBannerBlock
    | ImageCardGridBlock
    | StatsSectionBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Text alternativ pentru accesibilitate - obligatoriu pentru conformitatea WCAG
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Alege cum ar trebui afișat link-ul.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  googleMaps?: {
    /**
     * Copiază URL-ul de embed de la Google Maps (src="..." din iframe)
     */
    embedUrl?: string | null;
    /**
     * Înălțimea hărții în pixeli (200-800px)
     */
    height?: number | null;
  };
  /**
   * Adaugă programul de lucru pentru fiecare zi
   */
  businessHours?:
    | {
        day: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Adaugă link-uri către rețelele sociale
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'linkedin' | 'youtube' | 'tiktok' | 'other';
        url: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Alege cum să fie aranjate elementele
   */
  layout?: ('grid' | 'split') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        /**
         * Alege cum să fie aliniat textul în această coloană
         */
        textAlign?: ('left' | 'center' | 'right' | 'justify') | null;
        /**
         * Controlează mărimea și stilul textului din această coloană
         */
        typography?: {
          headingSize?: ('xs' | 'sm' | 'default' | 'lg' | 'xl' | '2xl') | null;
          bodySize?: ('xs' | 'sm' | 'default' | 'lg' | 'xl') | null;
        };
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Alege cum ar trebui afișat link-ul.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  displaySettings?: {
    cardStyle?: ('default' | 'minimal' | 'imageFocus') | null;
    showDate?: boolean | null;
    showDescription?: boolean | null;
    showCategories?: boolean | null;
    aspectRatio?: ('16/9' | '4/3' | '1/1' | '3/4') | null;
    /**
     * Text pentru butonul/link-ul de acțiune
     */
    buttonText?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileListBlock".
 */
export interface FileListBlock {
  /**
   * Titlul principal pentru lista de fișiere (opțional)
   */
  title?: string | null;
  files?:
    | {
        /**
         * Numele care va fi afișat pentru acest fișier
         */
        title: string;
        /**
         * Selectează fișierul (PDF, DOC, XLS, etc.)
         */
        file: string | Media;
        /**
         * Descriere opțională pentru fișier
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  style?: ('list' | 'cards' | 'compact') | null;
  /**
   * Alege câte coloane să fie afișate pentru lista de fișiere
   */
  columns?: ('1' | '2') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fileList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Titlul principal pentru galerie (opțional)
   */
  title?: string | null;
  /**
   * Descriere pentru galerie (opțional)
   */
  description?: string | null;
  images?:
    | {
        /**
         * Selectează imaginea pentru galerie
         */
        image: string | Media;
        /**
         * Titlu/descriere pentru imagine (opțional)
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('masonry' | 'grid' | 'featured') | null;
  columns?: ('auto' | '2' | '3' | '4' | '5') | null;
  /**
   * Permite vizualizarea imaginilor în modul lightbox la click
   */
  enableLightbox?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListBlock".
 */
export interface ListBlock {
  /**
   * Titlul principal pentru această listă
   */
  title?: string | null;
  /**
   * Un subtitlu opțional pentru mai mult context
   */
  subtitle?: string | null;
  /**
   * Alege în câte coloane să fie afișate elementele listei
   */
  columns?: ('1' | '2' | '3') | null;
  /**
   * Alege cum să fie stilizate elementele listei
   */
  listStyle?: ('card' | 'simple' | 'bordered') | null;
  /**
   * Adaugă elementele pentru această listă
   */
  items?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Alege cum ar trebui afișat link-ul.
           */
          appearance?: ('default' | 'outline') | null;
        };
        /**
         * Adaugă o iconiță pentru acest element de listă
         */
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Alege culoarea de fundal pentru întreaga secțiune
   */
  backgroundColor?: ('transparent' | 'gray-light' | 'blue-light' | 'green-light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title?: string | null;
  /**
   * Urmărește evoluția instituției noastre de-a lungul anilor
   */
  subtitle?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Adaugă evenimentele importante din istoria instituției în ordine cronologică
   */
  events: {
    /**
     * Anul evenimentului
     */
    year: string;
    /**
     * Titlul scurt al evenimentului
     */
    title: string;
    /**
     * Descrierea completă a evenimentului (opțional)
     */
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  layout?: {
    /**
     * Cum să fie afișat timeline-ul
     */
    style?: ('auto' | 'vertical') | null;
  };
  background?: {
    type?: ('color' | 'image' | 'none') | null;
    /**
     * Imaginea care va fi folosită ca fundal
     */
    image?: (string | null) | Media;
    /**
     * Overlay-ul care va fi aplicat peste imagine pentru a îmbunătăți citibilitatea textului
     */
    overlay?: ('none' | 'dark' | 'light') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  description?: string | null;
  width?: ('small' | 'medium' | 'large' | 'xlarge' | 'full') | null;
  showSearch?: boolean | null;
  searchPlaceholder?: string | null;
  style?: {
    backgroundColor?: ('none' | 'light' | 'dark' | 'primary') | null;
    questionStyle?: ('normal' | 'medium' | 'semibold' | 'bold') | null;
    showDividers?: boolean | null;
  };
  faqItems: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    defaultOpen?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock".
 */
export interface HeroBannerBlock {
  /**
   * Upload an icon for the banner (SVG recommended)
   */
  icon?: (string | null) | Media;
  /**
   * Use text instead of an icon (e.g., emoji or character)
   */
  iconText?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Background image for split screen layout or visual element for other themes
   */
  backgroundMedia?: (string | null) | Media;
  style?: {
    alignment?: ('left' | 'center') | null;
    size?: ('small' | 'medium' | 'large') | null;
    /**
     * Choose the style and layout for the hero banner
     */
    backgroundTheme?: ('modern' | 'split' | 'card') | null;
    /**
     * Control how the icon and title are positioned
     */
    layout?: ('default' | 'stacked') | null;
    /**
     * Control the size of the main title
     */
    titleSize?: ('normal' | 'large' | 'xl') | null;
  };
  link?: {
    url?: string | null;
    label?: string | null;
    /**
     * Choose the visual style of the call-to-action button
     */
    style?: ('solid' | 'outline' | 'ghost' | 'modern') | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCardGridBlock".
 */
export interface ImageCardGridBlock {
  title?: string | null;
  description?: string | null;
  width?: ('medium' | 'large' | 'xlarge' | 'full') | null;
  style?: {
    backgroundColor?: ('none' | 'light' | 'dark' | 'primary') | null;
    cardStyle?: ('shadow' | 'border' | 'minimal') | null;
    columns?: ('2' | '3' | '4') | null;
  };
  /**
   * Add image cards with photos, icons, titles, and descriptions
   */
  cards: {
    /**
     * Main image for the card (recommended: 16:9 aspect ratio)
     */
    image: string | Media;
    /**
     * Small icon for the card title (SVG recommended)
     */
    icon?: (string | null) | Media;
    /**
     * Use text/emoji instead of an icon
     */
    iconText?: string | null;
    title: string;
    description: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    link?: {
      url?: string | null;
      label?: string | null;
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageCardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsSectionBlock".
 */
export interface StatsSectionBlock {
  layout?: {
    textPosition?: ('left' | 'right' | 'center') | null;
    statsCount?: ('2' | '4' | '6') | null;
  };
  background?: {
    /**
     * Fundalul solid se adaptează automat la tema (gri deschis/întunecat)
     */
    type?: ('solid' | 'image') | null;
    /**
     * Imaginea de fundal pentru secțiune
     */
    image?: (string | null) | Media;
    /**
     * Overlay pentru îmbunătățirea lizibilității textului peste imagine
     */
    overlay?: ('dark' | 'light' | 'none') | null;
  };
  content?: {
    /**
     * Titlul principal pentru secțiunea de statistici
     */
    title?: string | null;
    /**
     * Descrierea opțională pentru secțiunea de statistici
     */
    description?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Adaugă 2, 4, sau 6 statistici cu numere și etichete
   */
  stats: {
    /**
     * ex: "150+", "50K+", "99%"
     */
    number: string;
    /**
     * ex: "Organizații Partenere", "Utilizatori Deserviți"
     */
    label: string;
    icon?: (string | null) | Media;
    /**
     * Folosește emoji sau text în loc de iconiță încărcată
     */
    iconText?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        layout?: T;
        splitScreenRightContent?: T;
        blogPostsMode?: T;
        selectedBlogPosts?: T;
        contentAlignment?: T;
        backgroundStyle?: T;
        backgroundColor?: T;
        backgroundImage?: T;
        gradientColors?:
          | T
          | {
              from?: T;
              to?: T;
              direction?: T;
            };
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
            };
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        secondaryImage?: T;
        bottomText?: T;
        showDownArrow?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        fileList?: T | FileListBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        list?: T | ListBlockSelect<T>;
        textImage?:
          | T
          | {
              layout?: T;
              designStyle?: T;
              content?:
                | T
                | {
                    heading?: T;
                    headingSize?: T;
                    subheading?: T;
                    eyebrow?: T;
                    text?: T;
                    buttons?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                reference?: T;
                                url?: T;
                              };
                          label?: T;
                          style?: T;
                          id?: T;
                        };
                  };
              image?: T;
              imageAspect?: T;
              verticalAlignment?: T;
              backgroundColor?: T;
              spacing?: T;
              imageStyle?:
                | T
                | {
                    borderRadius?: T;
                    shadow?: T;
                    overlay?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?: T | TimelineBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        heroBanner?: T | HeroBannerBlockSelect<T>;
        imageCardGrid?: T | ImageCardGridBlockSelect<T>;
        statsSection?: T | StatsSectionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  googleMaps?:
    | T
    | {
        embedUrl?: T;
        height?: T;
      };
  businessHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        textAlign?: T;
        typography?:
          | T
          | {
              headingSize?: T;
              bodySize?: T;
            };
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  displaySettings?:
    | T
    | {
        cardStyle?: T;
        showDate?: T;
        showDescription?: T;
        showCategories?: T;
        aspectRatio?: T;
        buttonText?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FileListBlock_select".
 */
export interface FileListBlockSelect<T extends boolean = true> {
  title?: T;
  files?:
    | T
    | {
        title?: T;
        file?: T;
        description?: T;
        id?: T;
      };
  style?: T;
  columns?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  columns?: T;
  enableLightbox?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListBlock_select".
 */
export interface ListBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  columns?: T;
  listStyle?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        icon?: T;
        id?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  events?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        style?: T;
      };
  background?:
    | T
    | {
        type?: T;
        image?: T;
        overlay?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  width?: T;
  showSearch?: T;
  searchPlaceholder?: T;
  style?:
    | T
    | {
        backgroundColor?: T;
        questionStyle?: T;
        showDividers?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        defaultOpen?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBannerBlock_select".
 */
export interface HeroBannerBlockSelect<T extends boolean = true> {
  icon?: T;
  iconText?: T;
  title?: T;
  description?: T;
  backgroundMedia?: T;
  style?:
    | T
    | {
        alignment?: T;
        size?: T;
        backgroundTheme?: T;
        layout?: T;
        titleSize?: T;
      };
  link?:
    | T
    | {
        url?: T;
        label?: T;
        style?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCardGridBlock_select".
 */
export interface ImageCardGridBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  width?: T;
  style?:
    | T
    | {
        backgroundColor?: T;
        cardStyle?: T;
        columns?: T;
      };
  cards?:
    | T
    | {
        image?: T;
        icon?: T;
        iconText?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              url?: T;
              label?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsSectionBlock_select".
 */
export interface StatsSectionBlockSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        textPosition?: T;
        statsCount?: T;
      };
  background?:
    | T
    | {
        type?: T;
        image?: T;
        overlay?: T;
      };
  content?:
    | T
    | {
        title?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        icon?: T;
        iconText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  /**
   * Configurează logo-ul și textul din partea stângă a header-ului
   */
  branding?: {
    showLogo?: boolean | null;
    showText?: boolean | null;
    brandText?: string | null;
    linkToHome?: boolean | null;
  };
  /**
   * Configurează butonul de căutare din header
   */
  search?: {
    showSearch?: boolean | null;
    /**
     * URL-ul către pagina de căutare (ex: /cautare)
     */
    searchUrl?: string | null;
  };
  /**
   * Personalizează aspectul header-ului
   */
  styling?: {
    backgroundType?: ('transparent' | 'semi-transparent' | 'solid') | null;
    layout?: ('container' | 'full-width') | null;
    buttonStyle?: {
      activeStyle?: ('button' | 'underline') | null;
      roundness?: ('none' | 'small' | 'medium' | 'large' | 'full') | null;
    };
  };
  /**
   * Adaugă elementele principale ale meniului (ex: Concursuri, Serbări, Orare). Poți avea fie un link simplu, fie un dropdown cu pagini dedesubt.
   */
  navItems?:
    | {
        label: string;
        type: 'link' | 'dropdown';
        singleLink?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
        };
        dropdownStyle?: ('standard' | 'with-descriptions') | null;
        submenu?:
          | {
              label: string;
              pageLink?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null);
                url?: string | null;
              };
              description?: string | null;
              showNewBadge?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Adaugă între 3-5 coloane pentru footer. Fiecare coloană poate conține text, logo, linkuri sau social media.
   */
  columns?:
    | {
        type: 'logoAndText' | 'linkList' | 'socialMedia' | 'contactInfo' | 'customText';
        logoText?: {
          showLogo?: boolean | null;
          title?: string | null;
          description?: string | null;
        };
        linkList?: {
          title: string;
          links?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'posts';
                        value: string | Post;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        socialMedia?: {
          title?: string | null;
          platforms?:
            | {
                platform:
                  | 'facebook'
                  | 'instagram'
                  | 'youtube'
                  | 'twitter'
                  | 'linkedin'
                  | 'tiktok'
                  | 'whatsapp'
                  | 'email';
                url: string;
                /**
                 * Dacă nu este completat, se va folosi numele platformei
                 */
                label?: string | null;
                id?: string | null;
              }[]
            | null;
        };
        contactInfo?: {
          title?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          schedule?:
            | {
                label: string;
                time: string;
                id?: string | null;
              }[]
            | null;
        };
        customText?: {
          title?: string | null;
          /**
           * Poți adăuga text formatat, linkuri, etc.
           */
          content?: {
            root: {
              type: string;
              children: {
                type: string;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
        };
        id?: string | null;
      }[]
    | null;
  bottomSection?: {
    copyrightText?: string | null;
    bottomLinks?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
    showThemeSelector?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  backToTop?: {
    /**
     * Show a button to scroll back to top on long pages
     */
    enabled?: boolean | null;
    /**
     * Number of pixels to scroll before showing the button
     */
    showAfterScroll?: number | null;
    position?: ('bottom-right' | 'bottom-left') | null;
  };
  themeToggle?: {
    /**
     * Display theme toggle button in the header for quick access
     */
    showInHeader?: boolean | null;
    /**
     * Display theme toggle button in the footer
     */
    showInFooter?: boolean | null;
  };
  siteName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        showLogo?: T;
        showText?: T;
        brandText?: T;
        linkToHome?: T;
      };
  search?:
    | T
    | {
        showSearch?: T;
        searchUrl?: T;
      };
  styling?:
    | T
    | {
        backgroundType?: T;
        layout?: T;
        buttonStyle?:
          | T
          | {
              activeStyle?: T;
              roundness?: T;
            };
      };
  navItems?:
    | T
    | {
        label?: T;
        type?: T;
        singleLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        dropdownStyle?: T;
        submenu?:
          | T
          | {
              label?: T;
              pageLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
              description?: T;
              showNewBadge?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        type?: T;
        logoText?:
          | T
          | {
              showLogo?: T;
              title?: T;
              description?: T;
            };
        linkList?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
        socialMedia?:
          | T
          | {
              title?: T;
              platforms?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    label?: T;
                    id?: T;
                  };
            };
        contactInfo?:
          | T
          | {
              title?: T;
              address?: T;
              phone?: T;
              email?: T;
              schedule?:
                | T
                | {
                    label?: T;
                    time?: T;
                    id?: T;
                  };
            };
        customText?:
          | T
          | {
              title?: T;
              content?: T;
            };
        id?: T;
      };
  bottomSection?:
    | T
    | {
        copyrightText?: T;
        bottomLinks?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        showThemeSelector?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  backToTop?:
    | T
    | {
        enabled?: T;
        showAfterScroll?: T;
        position?: T;
      };
  themeToggle?:
    | T
    | {
        showInHeader?: T;
        showInFooter?: T;
      };
  siteName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}